node {
    def EC2_HOST = 'ubuntu@13.211.58.33'
    def DEPLOY_PATH = '/home/ubuntu/react-app'

    stage('Checkout') {
        checkout scm
    }

    docker.image('node:16-buster-slim').inside {
        stage('Build') {
            sh 'npm install'
            sh 'npm run build'
        }
        
        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }
    }
    
    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?', ok: 'Proceed'
    }
    
    stage('Deploy') {
        withEnv(["EC2_HOST=${EC2_HOST}", "DEPLOY_PATH=${DEPLOY_PATH}"]) {
            sh '''
                chmod +x ./jenkins/scripts/deploy.sh
                ./jenkins/scripts/deploy.sh
            '''
            
            echo 'Aplikasi sedang berjalan. Tunggu 1 menit sebelum dimatikan...'
            sleep(time: 60, unit: 'SECONDS')
            
            sh '''
                chmod +x ./jenkins/scripts/kill.sh
                ./jenkins/scripts/kill.sh
            '''
            
            echo 'Aplikasi berhasil dimatikan'
        }
    }
}
